### PR TITLE
Django 1.11 port

### PR DESCRIPTION
**Pull request by patfreeman**
Some fixes.

### CODE REVIEW

**Comment by patfreeman** [comment]
Been using some of this: http://timony.com/mickzblog/2017/09/27/migrate-django-1-4-to-1-11/

**Comment by patfreeman** [comment]
I  had to leave the static stuff in urls.py commented it out. didn't figure that one out yet.

**Comment by ph1l** [comment]
When submitting pull requests, please use a separate feature branch. For example: 
```
$ git st
On branch django-1.11-port

$ git checkout -b my-changes
Switched to a new branch 'my-changes'

$ git commit
[my-changes 6df7038] test
 1 file changed, 5 insertions(+), 3 deletions(-)

$ git push -u origin my-changes 
To github.com:ph1l/ocemr.git
 * [new branch]      my-changes -> my-changes
Branch 'my-changes' set up to track remote branch 'my-changes' from 'origin'.
```

Then submit a PR from my-changes -> django-1.11-port. When I merge your changes into the main feature branch, you can pull the changes from the main upstream feature branch ( django-1.11-port) and the fork another feature branch.

Thanks so much for contributing!

**Comment by ph1l** [comment]
Oh, and I threw a couple commits on top of your changes, be sure to pull down the latest changes on `django-1.11-port`

**Pull request merged**
